### PR TITLE
Screenshot update & docs tweaking 

### PR DESCRIPTION
**Pull request by glynhudson**
What do you think about moving the 'dev' branch to its own repo called something like openevse-wifi -2.0 ? My branch of the dev firmware has been super stable for me for the past few days, however since it's such a large change maybe it would be worth giving it it's own repo and allowing users who just want a simpler setup to use to old 'stable' firmware. 

Do you think the ESP wifi firmware is ready to be moved to the OpenEVSE github?

### CODE REVIEW

**Comment by chris1howell** [comment]
Hi Glen,

Yeah I like both ideas. I will move both 1.0 and 2.0 to the OpenEVSE repo.

Chris

**Comment by glynhudson** [comment]
Great! Would it be possible to to give me push access to the 2.0 repo? I
will keep any significant changes in features branches and check with you
before merging into 2.0 master? Or I can keep raising PR's?

**Comment by chris1howell** [comment]
Yeah absolutely. I will set it up tomorrow.

On Mar 1, 2017 4:38 PM, "Glyn Hudson" <notifications@github.com<mailto:notifications@github.com>> wrote:
Great! Would it be possible to to give me push access to the 2.0 repo? I
will keep any significant changes in features branches and check with you
before merging into 2.0 master? Or I can keep raising PR's?

**Comment by ghost** [comment]
Just wanted to say thanks to both of you for all the work!

**Comment by glynhudson** [comment]
Sounds great @chris1howell . Could you merge this PR before moving the repo? It could get messy otherwise!

**Pull request merged**
