### PR TITLE
Emoncms

### PR DESCRIPTION
**Pull request by kronenpj**
Suggestion for ability to use any EMonCMS host, not just OpenEVSE. Default remains, but leaves option open for self-hosted or combined with pre-existing EMonCMS service for home utilization.

### CODE REVIEW

**Comment by kronenpj** [comment]
I should definitely mention that this is untested. I believe it to be correct but haven't tried it on the hardware. Sorry...

**Comment by chris1howell** [comment]
I added a couple lines over in the Development Branch to allow easy selection at compile time.

const char\* host = "data.openevse.com";
//const char\* host = "www.emoncms.org";
//const char\* host = "192.168.1.123";

**Comment by kronenpj** [comment]
It's up to you. I was trying to make it easier for those without the ability to flash the module.

**Comment by chris1howell** [comment]
Currently, I would like to keep a balance that favors novice users and keep the configuration as simple as possible. For power users that are able to build their own EmonCMS server should have no problem compiling and loading the firmware.

**Comment by chris1howell** [comment]
The latest commit (in development) adds firmware update via the webserver using /update. THis will make updating simple over WiFi. I will update code to the interface in a future commit.

**Comment by kronenpj** [comment]
I'm rescinding this patch - it doesn't work.

**Pull request closed without merging**
